Repository fastcampus-mini/credit-market-FE, pull requests merged in 2023-02, with the labels that each got.

#7 HOME UI / UX
  package-lock.json
  package.json
  public/images/logo_Main.png
  public/images/logo_white.png
  public/images/test-cat.jpg
  src/App.tsx
  src/components/common/Header.tsx
  src/components/common/Loading.tsx
  src/components/common/Navbar.tsx
  src/pages/Cart.tsx
  src/pages/Home.tsx
  src/routes/Router.tsx
  src/styles/GlobalStyle.tsx
Labels: feature

#17 Feat: 경로에 따른 Navbar 이동 수정 완료
  src/App.tsx
  src/apis/mypage.ts
  src/components/common/Header.tsx
  src/components/common/Navbar.tsx
  src/constants/apiUrls.ts
  src/constants/messages.ts
  src/constants/routes.ts
  src/pages/Mypage.tsx
  src/routes/Router.tsx
  src/styles/GlobalStyle.tsx
Labels: feature

#22 로그인, 회원가입 버튼 추가
  README.md
  src/components/common/Header.tsx
  src/components/common/Loading.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/SignIn.tsx
  src/routes/Router.tsx
  src/styles/GlobalStyle.tsx
Labels: feature

#44 Feat: 페이지별 내브바 이동 수정
  src/apis/mypage.ts
  src/components/common/Header.tsx
  src/components/common/Navbar.tsx
  src/pages/Mypage.tsx
  src/utils/path.ts
Labels: Refactor

#85 Feat: 로그인, 회원가입 페이지 input 애니메이션 추가
  README.md
  src/components/common/BackButton.tsx
  src/components/common/Input.tsx
  src/pages/Login.tsx
  src/pages/MyInfo.tsx
  src/pages/Mypage.tsx
  src/pages/Signup.tsx
Labels: feature

#86 Feat: input에 값이 있으면 focus 유지
  src/components/common/Input.tsx
  src/pages/Login.tsx
  src/pages/Signup.tsx
Labels: feature

#89 Refactor: 모달창 리덕스 상태로 관리하도록 리팩토링
  src/App.tsx
  src/components/Product/CartButton.tsx
  src/components/Product/ProductCard.tsx
  src/components/common/Button.tsx
  src/components/template/ModalBox.tsx
  src/components/template/Navbar.tsx
  src/constants/messages.ts
  src/interfaces/modal.ts
  src/interfaces/store.ts
  src/pages/Buy.tsx
  src/pages/Cart.tsx
  src/pages/Home.tsx
  src/pages/MyInfo.tsx
  src/pages/ProductDetail.tsx
  src/pages/Search.tsx
  src/pages/Signup.tsx
  src/store/modalSlice.ts
  src/store/store.ts
Labels: Refactor

#98 Fix: 신청 페이지 더미데이터 수정
  src/pages/Buy.tsx
Labels: fix

#96 Feat : 관심상품 페이지 구현 시작
  src/components/common/MyFavCard.tsx
  src/pages/MyFavor.tsx
Labels: feature

#99 Fix: 장바구니 슬라이스에 인터페이스 적용
  src/store/cartSlice.ts
Labels: fix

#101 Feat: 버튼 title 추가
  src/components/Product/CartButton.tsx
  src/components/Product/FavorButton.tsx
Labels: feature

#104 Feat: Input 애니메이션 Select에도 적용
  src/components/Product/CartButton.tsx
  src/components/common/Input.tsx
  src/pages/Login.tsx
  src/pages/Signup.tsx
Labels: feature

#111 Design: mypage 레이아웃 수정
  package-lock.json
  src/pages/Home.tsx
  src/pages/Mypage.tsx
  src/pages/Signup.tsx
Labels: design

#112 Design: 장바구니 카드 스타일 수정
  src/apis/cart.ts
  src/components/Cart/CartItem.tsx
  src/components/Product/FavorButton.tsx
  src/components/common/Button.tsx
  src/pages/Buy.tsx
  src/pages/Cart.tsx
Labels: style

#115 Design: password modal 수정
  src/components/template/PasswordModalBox.tsx
  src/pages/MyInfo.tsx
  src/pages/Signup.tsx
  src/styles/GlobalStyle.tsx
Labels: design

#117 Design: 신청상품 페이지 신청취소 버튼 생성 & Fix: 타입스크립트 버그 수정
  src/components/common/ProductCardBuy.tsx
  src/components/common/ProductCardFav.tsx
  src/pages/MyBuy.tsx
  src/pages/MyFavor.tsx
Labels: bug, design

#120 Design: 비밀번호 검증 모달창 수정
  src/components/template/PasswordModalBox.tsx
  src/constants/messages.ts
Labels: style

#119 Feat: axios를 활용한 로그인 기능 구현
  package-lock.json
  package.json
  src/components/template/PasswordModalBox.tsx
  src/interfaces/user.ts
  src/main.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/MyInfo.tsx
  src/pages/Signup.tsx
Labels: feature, fix

#122 Fix: react-cookie 재설치
  package-lock.json
  package.json
  src/pages/Home.tsx
Labels: fix

#123 Feat: 경로 보호 컴포넌트 적용
  src/constants/messages.ts
  src/routes/PrivateRoute.tsx
Labels: feature

#124 Feat: 장바구니에 상품이 없을 경우 분기 처리
  src/lotties/animated-shopping-cart.json
  src/pages/Cart.tsx
Labels: feature

#125 Fix: 경로 보호 컴포넌트 타입 에러 수정
  src/routes/PrivateRoute.tsx
Labels: fix

#126 Feat: 장바구니 버튼 회원/비회원 분기처리
  src/components/Product/CartButton.tsx
  src/components/template/ModalBox.tsx
  src/interfaces/modal.ts
  src/store/modalSlice.ts
Labels: feature

#127 Feat: 관심상품 추가 버튼 회원/비회원 분기처리
  src/components/Product/FavorButton.tsx
Labels: feature

#128 Design: 은행로고 추가
  public/images/banks/bc.png
  public/images/banks/bnk.png
  public/images/banks/busan_kyungnam.png
  public/images/banks/db.png
  public/images/banks/eq.png
  public/images/banks/hansung.png
  public/images/banks/hundai.png
  public/images/banks/hyundai.png
  public/images/banks/jinju.png
  public/images/banks/jt.png
  public/images/banks/lotte.png
  public/images/banks/ok.png
  public/images/banks/osb.png
  public/images/banks/peper.png
  public/images/banks/sangsang.png
  public/images/banks/sbi.png
  public/images/banks/seram.png
  public/images/banks/sh.png
  public/images/banks/volks.png
  public/images/banks/welcome.png
  public/images/banks/yegaram.png
  src/apis/auth.ts
  src/components/Product/ProductCard.tsx
  src/components/common/LogoutButton.tsx
  src/utils/bankLogo.ts
Labels: design

#129 Refactor: 모달창 합침 (공통 모달 + 비밀번호 모달) / 로그인, 회원가입 인터페이스 적용
  src/App.tsx
  src/components/common/Button.tsx
  src/components/template/ModalBox.tsx
  src/components/template/PasswordModalBox.tsx
  src/interfaces/modal.ts
  src/interfaces/store.ts
  src/interfaces/user.ts
  src/pages/Login.tsx
  src/pages/MyInfo.tsx
  src/pages/Signup.tsx
  src/store/passModalSlice.ts
  src/store/store.ts
Labels: Refactor

#131 Fix: 상품 인터페이스 수정
  src/apis/cart.ts
  src/constants/apiUrls.ts
  src/interfaces/product.ts
  src/pages/Cart.tsx
  src/pages/Home.tsx
  src/pages/ProductDetail.tsx
  src/pages/Search.tsx
Labels: fix

#134 Refactor: 회원가입 기능 리팩토링
  src/components/common/LogoutButton.tsx
  src/constants/messages.ts
  src/interfaces/user.ts
  src/pages/MyInfo.tsx
  src/pages/Signup.tsx
Labels: bug, Refactor

#135 Fix: 로그아웃 시 쿠키 삭제
  src/components/template/Header.tsx
  src/constants/messages.ts
Labels: fix

#136 Feat: 랜덤 상품 임시 mock 데이터 추가
  public/mockData/randomProducts.json
  src/pages/Home.tsx
Labels: feature

#138 Fix: 추천 상품 에러 수정
  src/pages/Home.tsx
Labels: fix

#140 Refactor: RootState 타입 추가
  src/components/Product/CartButton.tsx
  src/components/template/Loading.tsx
  src/components/template/ModalBox.tsx
  src/interfaces/store.ts
  src/store/modalSlice.ts
  src/store/store.ts
Labels: Refactor

#139 Refactor: 관심 상품 페이지 관련 파일들 리팩토링
  src/components/common/ProductCardFav.tsx
  src/interfaces/favor.ts
  src/pages/MyFavor.tsx
Labels: Refactor

#141 Fix: 모달 더블 클릭 에러 및 회원가입 데이터 저장 오류 수정, 이메일 중복 알림 모달 생성
  src/components/template/ModalBox.tsx
  src/pages/Login.tsx
  src/pages/Signup.tsx
Labels: feature, fix

#144 Design: 로딩 컴포넌트가 모달창 위로 올라오도록 수정
  src/components/template/Loading.tsx
Labels: style

#143 Feat: 로그인 시 이메일, 비밀번호 체크 모달 생성, 쿠키 만료 시간 설정
  src/pages/Login.tsx
Labels: feature

#145 Feat: 신청 페이지 이동 시 상품 데이터 가져가도록 수정
  src/apis/buy.ts
  src/apis/cart.ts
  src/apis/favor.ts
  src/apis/product.ts
  src/components/Cart/CartItem.tsx
  src/components/Product/CartButton.tsx
  src/components/Product/ProductCard.tsx
  src/constants/apiUrls.ts
  src/constants/messages.ts
  src/interfaces/cart.ts
  src/interfaces/product.ts
  src/pages/Buy.tsx
  src/pages/Cart.tsx
  src/pages/ProductDetail.tsx
  src/store/cartSlice.ts
Labels: feature

#146 Feat: 장바구니 선택삭제 버튼 클릭 시 선택한 상품 개수 체크
  src/pages/Cart.tsx
Labels: feature

#147 Env: API 요청 baseUrl 변경
  .env
Labels: env

#150 Feat: 장바구니 추가 기능 구현
  .env
  src/apis/cart.ts
  src/components/Cart/CartItem.tsx
  src/components/Product/CartButton.tsx
  src/components/Product/ProductCard.tsx
  src/interfaces/cart.ts
  src/interfaces/product.ts
  src/pages/Cart.tsx
  src/pages/ProductDetail.tsx
Labels: feature

#149 Design: 로그인, 회원가입 페이지 리디자인
  src/components/common/BackButton.tsx
  src/components/common/Button.tsx
  src/components/common/Input.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/Signup.tsx
  src/styles/GlobalStyle.tsx
Labels: design

#151 Feat: 장바구니 선택 삭제 / 단일 삭제 기능 구현
  src/apis/cart.ts
  src/components/Cart/CartItem.tsx
  src/components/Product/CartButton.tsx
  src/interfaces/cart.ts
  src/pages/Buy.tsx
  src/pages/Cart.tsx
Labels: feature

#152 Fix: 쿠키에 옵션값이 올바르게 들어가도록 수정
  src/utils/cookie.ts
Labels: fix

#155 Feat: 상품 신청 기능 구현
  src/pages/Buy.tsx
  src/pages/Cart.tsx
  src/pages/ProductDetail.tsx
Labels: feature

#157 Fix: 상품 상세에서 신청 페이지로 이동하여 신청할 경우 에러 수정
  src/pages/Buy.tsx
Labels: fix

#158 Fix: 장바구니 선택 상품 카운트 에러 수정
  src/components/Cart/CartItem.tsx
  src/pages/Cart.tsx
Labels: fix

#160 Env: API 요청 baseUrl https 로 수정
  .env
Labels: env

#162 Feat: 관심 상품 추가 / 삭제 기능 구현
  src/apis/favor.ts
  src/components/Cart/CartItem.tsx
  src/components/Product/CartButton.tsx
  src/components/Product/FavorButton.tsx
  src/components/Product/ProductCard.tsx
  src/components/common/ProductCardFav.tsx
  src/constants/messages.ts
Labels: feature

#166 Feat: 검색 기능 구현
  src/apis/product.ts
  src/components/common/Input.tsx
  src/components/common/LogoutButton.tsx
  src/components/template/Header.tsx
  src/constants/apiUrls.ts
  src/constants/messages.ts
  src/interfaces/Search.ts
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/Search.tsx
  src/pages/Signup.tsx
  src/store/SearchSlice.ts
  src/store/reduxProducts.ts
  src/store/store.ts
Labels: bug, feature

#168 Refactor: 관심상품 목록 리덕스로 관리하도록 수정
  src/components/Product/FavorButton.tsx
  src/components/Product/ProductCard.tsx
  src/constants/messages.ts
  src/pages/MyFavor.tsx
  src/store/cartSlice.ts
  src/store/favorSlice.ts
  src/store/store.ts
Labels: Refactor

#167 Design: 검색페이지 selectBox 수정
  src/pages/Search.tsx
Labels: design

#171 Docs: 리드미 파일 수정 (구조 삭제 및 구현 기능 추가)
  README.md
Labels: docu

#172 Docs: 리드미 파일에 백엔드 저장소 링크 추가
  README.md
Labels: docu

#173 Fix: 검색 엔진 오류 수정
  src/components/common/Input.tsx
  src/constants/apiUrls.ts
  src/pages/Home.tsx
  src/pages/Search.tsx
Labels: fix

#178 Feat: 비밀번호 인증 기능 구현중
  src/apis/auth.ts
  src/constants/apiUrls.ts
  src/constants/messages.ts
  src/pages/Login.tsx
  src/pages/MyInfo.tsx
  src/pages/Mypage.tsx
  src/pages/Search.tsx
  src/pages/Signup.tsx
  src/store/modalSlice.ts
Labels: bug, feature

#179 Fix: 중복 모달 삭제
  src/pages/MyInfo.tsx
  src/pages/Mypage.tsx
Labels: fix

#184 Refactor: 신청상품 요청 데이터 배열 타입으로 변경
  src/apis/buy.ts
  src/components/Product/ProductCard.tsx
  src/interfaces/buy.ts
  src/pages/MyBuy.tsx
Labels: feature, Refactor

#182 Design: Home 배너 회원멘트 수정 & Refactor: Navbar리팩토링
  .env
  src/App.tsx
  src/ProductCardBuy.tsx
  src/components/Product/FavorButton.tsx
  src/components/Product/ProductCard.tsx
  src/components/template/Header.tsx
  src/components/template/Navbar.tsx
  src/components/template/Navbar/Bubble.tsx
  src/components/template/Navbar/Navbar.tsx
  src/components/template/Navbar/NavbarMove.ts
  src/components/template/Navbar/NavbarUI.tsx
  src/interfaces/buy.ts
  src/interfaces/favor.ts
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/MyBuy.tsx
  src/pages/MyFavor.tsx
  src/pages/Search.tsx
  src/pages/Signup.tsx
  src/routes/Router.tsx
  src/store/favorSlice.ts
  src/store/myBuySlice.ts
  src/store/store.ts
  src/styles/GlobalStyle.tsx
Labels: feature, Refactor, design

#185 Feat: 마이페이지 신청상품 페이지
  src/apis/buy.ts
  src/components/Product/ProductCard.tsx
  src/components/common/Button.tsx
  src/components/common/ProductCardFav.tsx
  src/interfaces/buy.ts
  src/lotties/BuyLottie.json
  src/pages/MyBuy.tsx
  src/store/myBuySlice.ts
Labels: feature

#186 Design: 신청취소 버튼 수정
  src/components/Product/ProductCard.tsx
  src/components/common/Button.tsx
  src/pages/MyBuy.tsx
Labels: design

#194 Feat: 아바타 변경
  package-lock.json
  package.json
  src/components/template/AvatarIcon.tsx
  src/components/template/Header.tsx
  src/pages/Mypage.tsx
Labels: feature

#195 Rename: 인터페이스 파일명 변경
  src/apis/product.ts
  src/constants/apiUrls.ts
  src/pages/Search.tsx
Labels: Refactor

#204 Fix: welcome 페이지 이름 기능 수정
  src/pages/Welcome.tsx
Labels: fix
